version: '3.4'

services:
  accountingservice:
    image: accountingservice:dev
    container_name: AccountingService_1
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AccountingService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\gamma\OneDriveEFIF\OneDrive - EFIF\CPH Business\Software Development\4. System Integration\Assignment 3\AccountingService\AccountingService:/app
      - C:\Users\gamma\OneDriveEFIF\OneDrive - EFIF\CPH Business\Software Development\4. System Integration\Assignment 3\AccountingService:/src
      - C:\Users\gamma\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\gamma\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/AccountingService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true