// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Book.proto

package com.bookstore.grpc;

public final class Book {
  private Book() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BuyBookRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BuyBookRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 studentId = 1;</code>
     */
    int getStudentId();

    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     */
    boolean hasOrderDate();
    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     */
    com.google.protobuf.Timestamp getOrderDate();
    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getOrderDateOrBuilder();

    /**
     * <code>string isbn = 3;</code>
     */
    java.lang.String getIsbn();
    /**
     * <code>string isbn = 3;</code>
     */
    com.google.protobuf.ByteString
        getIsbnBytes();

    /**
     * <code>int32 bookPrice = 4;</code>
     */
    int getBookPrice();
  }
  /**
   * Protobuf type {@code BuyBookRequest}
   */
  public  static final class BuyBookRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BuyBookRequest)
      BuyBookRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BuyBookRequest.newBuilder() to construct.
    private BuyBookRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BuyBookRequest() {
      studentId_ = 0;
      isbn_ = "";
      bookPrice_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BuyBookRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              studentId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (orderDate_ != null) {
                subBuilder = orderDate_.toBuilder();
              }
              orderDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(orderDate_);
                orderDate_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              isbn_ = s;
              break;
            }
            case 32: {

              bookPrice_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bookstore.grpc.Book.internal_static_BuyBookRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bookstore.grpc.Book.internal_static_BuyBookRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bookstore.grpc.Book.BuyBookRequest.class, com.bookstore.grpc.Book.BuyBookRequest.Builder.class);
    }

    public static final int STUDENTID_FIELD_NUMBER = 1;
    private int studentId_;
    /**
     * <code>int32 studentId = 1;</code>
     */
    public int getStudentId() {
      return studentId_;
    }

    public static final int ORDERDATE_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp orderDate_;
    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     */
    public boolean hasOrderDate() {
      return orderDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     */
    public com.google.protobuf.Timestamp getOrderDate() {
      return orderDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderDate_;
    }
    /**
     * <code>.google.protobuf.Timestamp orderDate = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getOrderDateOrBuilder() {
      return getOrderDate();
    }

    public static final int ISBN_FIELD_NUMBER = 3;
    private volatile java.lang.Object isbn_;
    /**
     * <code>string isbn = 3;</code>
     */
    public java.lang.String getIsbn() {
      java.lang.Object ref = isbn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isbn_ = s;
        return s;
      }
    }
    /**
     * <code>string isbn = 3;</code>
     */
    public com.google.protobuf.ByteString
        getIsbnBytes() {
      java.lang.Object ref = isbn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isbn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOKPRICE_FIELD_NUMBER = 4;
    private int bookPrice_;
    /**
     * <code>int32 bookPrice = 4;</code>
     */
    public int getBookPrice() {
      return bookPrice_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (studentId_ != 0) {
        output.writeInt32(1, studentId_);
      }
      if (orderDate_ != null) {
        output.writeMessage(2, getOrderDate());
      }
      if (!getIsbnBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, isbn_);
      }
      if (bookPrice_ != 0) {
        output.writeInt32(4, bookPrice_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (studentId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, studentId_);
      }
      if (orderDate_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getOrderDate());
      }
      if (!getIsbnBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, isbn_);
      }
      if (bookPrice_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, bookPrice_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bookstore.grpc.Book.BuyBookRequest)) {
        return super.equals(obj);
      }
      com.bookstore.grpc.Book.BuyBookRequest other = (com.bookstore.grpc.Book.BuyBookRequest) obj;

      boolean result = true;
      result = result && (getStudentId()
          == other.getStudentId());
      result = result && (hasOrderDate() == other.hasOrderDate());
      if (hasOrderDate()) {
        result = result && getOrderDate()
            .equals(other.getOrderDate());
      }
      result = result && getIsbn()
          .equals(other.getIsbn());
      result = result && (getBookPrice()
          == other.getBookPrice());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STUDENTID_FIELD_NUMBER;
      hash = (53 * hash) + getStudentId();
      if (hasOrderDate()) {
        hash = (37 * hash) + ORDERDATE_FIELD_NUMBER;
        hash = (53 * hash) + getOrderDate().hashCode();
      }
      hash = (37 * hash) + ISBN_FIELD_NUMBER;
      hash = (53 * hash) + getIsbn().hashCode();
      hash = (37 * hash) + BOOKPRICE_FIELD_NUMBER;
      hash = (53 * hash) + getBookPrice();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bookstore.grpc.Book.BuyBookRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bookstore.grpc.Book.BuyBookRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bookstore.grpc.Book.BuyBookRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bookstore.grpc.Book.BuyBookRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bookstore.grpc.Book.BuyBookRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bookstore.grpc.Book.BuyBookRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bookstore.grpc.Book.BuyBookRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bookstore.grpc.Book.BuyBookRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bookstore.grpc.Book.BuyBookRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bookstore.grpc.Book.BuyBookRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bookstore.grpc.Book.BuyBookRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bookstore.grpc.Book.BuyBookRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bookstore.grpc.Book.BuyBookRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BuyBookRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BuyBookRequest)
        com.bookstore.grpc.Book.BuyBookRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bookstore.grpc.Book.internal_static_BuyBookRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bookstore.grpc.Book.internal_static_BuyBookRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bookstore.grpc.Book.BuyBookRequest.class, com.bookstore.grpc.Book.BuyBookRequest.Builder.class);
      }

      // Construct using com.bookstore.grpc.Book.BuyBookRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        studentId_ = 0;

        if (orderDateBuilder_ == null) {
          orderDate_ = null;
        } else {
          orderDate_ = null;
          orderDateBuilder_ = null;
        }
        isbn_ = "";

        bookPrice_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bookstore.grpc.Book.internal_static_BuyBookRequest_descriptor;
      }

      @java.lang.Override
      public com.bookstore.grpc.Book.BuyBookRequest getDefaultInstanceForType() {
        return com.bookstore.grpc.Book.BuyBookRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.bookstore.grpc.Book.BuyBookRequest build() {
        com.bookstore.grpc.Book.BuyBookRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bookstore.grpc.Book.BuyBookRequest buildPartial() {
        com.bookstore.grpc.Book.BuyBookRequest result = new com.bookstore.grpc.Book.BuyBookRequest(this);
        result.studentId_ = studentId_;
        if (orderDateBuilder_ == null) {
          result.orderDate_ = orderDate_;
        } else {
          result.orderDate_ = orderDateBuilder_.build();
        }
        result.isbn_ = isbn_;
        result.bookPrice_ = bookPrice_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bookstore.grpc.Book.BuyBookRequest) {
          return mergeFrom((com.bookstore.grpc.Book.BuyBookRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bookstore.grpc.Book.BuyBookRequest other) {
        if (other == com.bookstore.grpc.Book.BuyBookRequest.getDefaultInstance()) return this;
        if (other.getStudentId() != 0) {
          setStudentId(other.getStudentId());
        }
        if (other.hasOrderDate()) {
          mergeOrderDate(other.getOrderDate());
        }
        if (!other.getIsbn().isEmpty()) {
          isbn_ = other.isbn_;
          onChanged();
        }
        if (other.getBookPrice() != 0) {
          setBookPrice(other.getBookPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bookstore.grpc.Book.BuyBookRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bookstore.grpc.Book.BuyBookRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int studentId_ ;
      /**
       * <code>int32 studentId = 1;</code>
       */
      public int getStudentId() {
        return studentId_;
      }
      /**
       * <code>int32 studentId = 1;</code>
       */
      public Builder setStudentId(int value) {
        
        studentId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 studentId = 1;</code>
       */
      public Builder clearStudentId() {
        
        studentId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp orderDate_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> orderDateBuilder_;
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public boolean hasOrderDate() {
        return orderDateBuilder_ != null || orderDate_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public com.google.protobuf.Timestamp getOrderDate() {
        if (orderDateBuilder_ == null) {
          return orderDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : orderDate_;
        } else {
          return orderDateBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public Builder setOrderDate(com.google.protobuf.Timestamp value) {
        if (orderDateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          orderDate_ = value;
          onChanged();
        } else {
          orderDateBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public Builder setOrderDate(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (orderDateBuilder_ == null) {
          orderDate_ = builderForValue.build();
          onChanged();
        } else {
          orderDateBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public Builder mergeOrderDate(com.google.protobuf.Timestamp value) {
        if (orderDateBuilder_ == null) {
          if (orderDate_ != null) {
            orderDate_ =
              com.google.protobuf.Timestamp.newBuilder(orderDate_).mergeFrom(value).buildPartial();
          } else {
            orderDate_ = value;
          }
          onChanged();
        } else {
          orderDateBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public Builder clearOrderDate() {
        if (orderDateBuilder_ == null) {
          orderDate_ = null;
          onChanged();
        } else {
          orderDate_ = null;
          orderDateBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getOrderDateBuilder() {
        
        onChanged();
        return getOrderDateFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getOrderDateOrBuilder() {
        if (orderDateBuilder_ != null) {
          return orderDateBuilder_.getMessageOrBuilder();
        } else {
          return orderDate_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : orderDate_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp orderDate = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getOrderDateFieldBuilder() {
        if (orderDateBuilder_ == null) {
          orderDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getOrderDate(),
                  getParentForChildren(),
                  isClean());
          orderDate_ = null;
        }
        return orderDateBuilder_;
      }

      private java.lang.Object isbn_ = "";
      /**
       * <code>string isbn = 3;</code>
       */
      public java.lang.String getIsbn() {
        java.lang.Object ref = isbn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          isbn_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string isbn = 3;</code>
       */
      public com.google.protobuf.ByteString
          getIsbnBytes() {
        java.lang.Object ref = isbn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          isbn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string isbn = 3;</code>
       */
      public Builder setIsbn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        isbn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string isbn = 3;</code>
       */
      public Builder clearIsbn() {
        
        isbn_ = getDefaultInstance().getIsbn();
        onChanged();
        return this;
      }
      /**
       * <code>string isbn = 3;</code>
       */
      public Builder setIsbnBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        isbn_ = value;
        onChanged();
        return this;
      }

      private int bookPrice_ ;
      /**
       * <code>int32 bookPrice = 4;</code>
       */
      public int getBookPrice() {
        return bookPrice_;
      }
      /**
       * <code>int32 bookPrice = 4;</code>
       */
      public Builder setBookPrice(int value) {
        
        bookPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 bookPrice = 4;</code>
       */
      public Builder clearBookPrice() {
        
        bookPrice_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BuyBookRequest)
    }

    // @@protoc_insertion_point(class_scope:BuyBookRequest)
    private static final com.bookstore.grpc.Book.BuyBookRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bookstore.grpc.Book.BuyBookRequest();
    }

    public static com.bookstore.grpc.Book.BuyBookRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BuyBookRequest>
        PARSER = new com.google.protobuf.AbstractParser<BuyBookRequest>() {
      @java.lang.Override
      public BuyBookRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuyBookRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BuyBookRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BuyBookRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bookstore.grpc.Book.BuyBookRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface APIResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:APIResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responseMessage = 1;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <code>string responseMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();

    /**
     * <code>int32 responseCode = 2;</code>
     */
    int getResponseCode();
  }
  /**
   * Protobuf type {@code APIResponse}
   */
  public  static final class APIResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:APIResponse)
      APIResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use APIResponse.newBuilder() to construct.
    private APIResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private APIResponse() {
      responseMessage_ = "";
      responseCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private APIResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            case 16: {

              responseCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bookstore.grpc.Book.internal_static_APIResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bookstore.grpc.Book.internal_static_APIResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bookstore.grpc.Book.APIResponse.class, com.bookstore.grpc.Book.APIResponse.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseMessage_;
    /**
     * <code>string responseMessage = 1;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responseMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 2;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 2;</code>
     */
    public int getResponseCode() {
      return responseCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseMessage_);
      }
      if (responseCode_ != 0) {
        output.writeInt32(2, responseCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseMessage_);
      }
      if (responseCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, responseCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bookstore.grpc.Book.APIResponse)) {
        return super.equals(obj);
      }
      com.bookstore.grpc.Book.APIResponse other = (com.bookstore.grpc.Book.APIResponse) obj;

      boolean result = true;
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      result = result && (getResponseCode()
          == other.getResponseCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bookstore.grpc.Book.APIResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bookstore.grpc.Book.APIResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bookstore.grpc.Book.APIResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bookstore.grpc.Book.APIResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bookstore.grpc.Book.APIResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bookstore.grpc.Book.APIResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bookstore.grpc.Book.APIResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bookstore.grpc.Book.APIResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bookstore.grpc.Book.APIResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.bookstore.grpc.Book.APIResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bookstore.grpc.Book.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bookstore.grpc.Book.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bookstore.grpc.Book.APIResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code APIResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:APIResponse)
        com.bookstore.grpc.Book.APIResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bookstore.grpc.Book.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bookstore.grpc.Book.internal_static_APIResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bookstore.grpc.Book.APIResponse.class, com.bookstore.grpc.Book.APIResponse.Builder.class);
      }

      // Construct using com.bookstore.grpc.Book.APIResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseMessage_ = "";

        responseCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bookstore.grpc.Book.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      public com.bookstore.grpc.Book.APIResponse getDefaultInstanceForType() {
        return com.bookstore.grpc.Book.APIResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.bookstore.grpc.Book.APIResponse build() {
        com.bookstore.grpc.Book.APIResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bookstore.grpc.Book.APIResponse buildPartial() {
        com.bookstore.grpc.Book.APIResponse result = new com.bookstore.grpc.Book.APIResponse(this);
        result.responseMessage_ = responseMessage_;
        result.responseCode_ = responseCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bookstore.grpc.Book.APIResponse) {
          return mergeFrom((com.bookstore.grpc.Book.APIResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bookstore.grpc.Book.APIResponse other) {
        if (other == com.bookstore.grpc.Book.APIResponse.getDefaultInstance()) return this;
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        if (other.getResponseCode() != 0) {
          setResponseCode(other.getResponseCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.bookstore.grpc.Book.APIResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.bookstore.grpc.Book.APIResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <code>string responseMessage = 1;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }

      private int responseCode_ ;
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public int getResponseCode() {
        return responseCode_;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public Builder setResponseCode(int value) {
        
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 responseCode = 2;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:APIResponse)
    }

    // @@protoc_insertion_point(class_scope:APIResponse)
    private static final com.bookstore.grpc.Book.APIResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bookstore.grpc.Book.APIResponse();
    }

    public static com.bookstore.grpc.Book.APIResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<APIResponse>
        PARSER = new com.google.protobuf.AbstractParser<APIResponse>() {
      @java.lang.Override
      public APIResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new APIResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<APIResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<APIResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bookstore.grpc.Book.APIResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuyBookRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BuyBookRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nBook.proto\032\037google/protobuf/timestamp." +
      "proto\"s\n\016BuyBookRequest\022\021\n\tstudentId\030\001 \001" +
      "(\005\022-\n\torderDate\030\002 \001(\0132\032.google.protobuf." +
      "Timestamp\022\014\n\004isbn\030\003 \001(\t\022\021\n\tbookPrice\030\004 \001" +
      "(\005\"<\n\013APIResponse\022\027\n\017responseMessage\030\001 \001" +
      "(\t\022\024\n\014responseCode\030\002 \001(\00525\n\tbookStore\022(\n" +
      "\007buyBook\022\017.BuyBookRequest\032\014.APIResponseB" +
      "\024\n\022com.bookstore.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_BuyBookRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BuyBookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BuyBookRequest_descriptor,
        new java.lang.String[] { "StudentId", "OrderDate", "Isbn", "BookPrice", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
